#ifndef __OMNIBOT_MANIPULATOR_TELEOP_LIB_H__
#define __OMNIBOT_MANIPULATOR_TELEOP_LIB_H__

class OMNIBOT_MANIPULATOR_TELEOP_LIB
{
private:
    
public:
    OMNIBOT_MANIPULATOR_TELEOP_LIB();
    ~OMNIBOT_MANIPULATOR_TELEOP_LIB();
};



#endif // __OMNIBOT_MANIPULATOR_TELEOP_LIB_H__