#define SERIAL_BAUDRATE 9600
#define SERIAL_SEND_RATE_HZ 0.5

enum
{
    BATTERY_1,
    BATTERY_2,
    BATTERIES_COUNT
};

enum
{
    CELL_1,
    CELL_2,
    CELL_3,
    CELL_4,
    CELLS_COUNT
};
#define BATTERIES_SERIAL_CONFIGURATION CELLS_COUNT

#define BATTERY_1_CELL_1_PIN A0
#define BATTERY_1_CELL_2_PIN A1
#define BATTERY_1_CELL_3_PIN A2

#define BATTERY_2_CELL_1_PIN A3
#define BATTERY_2_CELL_2_PIN A4
#define BATTERY_2_CELL_3_PIN A5

#define RELAY_CONTROL_PIN 10

#define OFF LOW
#define ON HIGH


#define RESITOR_DIVIDER__R1_VAL_Om 100e3
#define RESITOR_DIVIDER__R2_VAL_Om 10e3
#define ADC_MAX_VALUE 1024
#define SOURCE_VOLTAGE_VOLTS 5.0

const int battery_1_cell_pins[BATTERIES_SERIAL_CONFIGURATION] = {
    BATTERY_1_CELL_1_PIN,
    BATTERY_1_CELL_2_PIN,
    BATTERY_1_CELL_3_PIN,
};

const int battery_2_cell_pins[BATTERIES_SERIAL_CONFIGURATION] = {
    BATTERY_2_CELL_1_PIN,
    BATTERY_2_CELL_2_PIN,
    BATTERY_2_CELL_3_PIN,
};



#define R1 RESITOR_DIVIDER__R1_VAL_Om
#define R2 RESITOR_DIVIDER__R2_VAL_Om