- ros_topic_name: "/left_front_mecanum_joint/velocity"
  gz_topic_name: "/left_front_mecanum_joint/velocity"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
  lazy: false

- ros_topic_name: "/right_front_mecanum_joint/velocity"
  gz_topic_name: "/right_front_mecanum_joint/velocity"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
  lazy: false

- ros_topic_name: "/left_back_mecanum_joint/velocity"
  gz_topic_name: "/left_back_mecanum_joint/velocity"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
  lazy: false

- ros_topic_name: "/right_back_mecanum_joint/velocity"
  gz_topic_name: "/right_back_mecanum_joint/velocity"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
  lazy: false

- ros_topic_name: "/joint_states"
  gz_topic_name: "/world/default/model/omnibot_robot/joint_state"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS

- ros_topic_name: "/scan"
  gz_topic_name: "/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS

###########################################################
#############REALSENSE_D435_CAMERA_BRIDGE##################
###########################################################
### common
- ros_topic_name: "/d435/depth/camera_info"
  gz_topic_name: "/d435/depth/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS
###########################################################
### depth 
- ros_topic_name: "/d435/depth/depth_image"
  gz_topic_name: "/d435/depth/depth_image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

- ros_topic_name: "/d435/depth/image"
  gz_topic_name: "/d435/depth/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

- ros_topic_name: "/d435/depth/points"
  gz_topic_name: "/d435/depth/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  direction: GZ_TO_ROS
# ###########################################################
# ### color 
# - ros_topic_name: "/d435/color/image_raw"
#   gz_topic_name: "/d435/color/image_raw"
#   ros_type_name: "sensor_msgs/msg/Image"
#   gz_type_name: "gz.msgs.Image"
#   direction: GZ_TO_ROS

# - ros_topic_name: "/d435/color/camera_info"
#   gz_topic_name: "/d435/color/camera_info"
#   ros_type_name: "sensor_msgs/msg/CameraInfo"
#   gz_type_name: "gz.msgs.CameraInfo"
#   direction: GZ_TO_ROS
# ###########################################################
# ### infra 1
# - ros_topic_name: "/d435/infra1/image_rect_raw"
#   gz_topic_name: "/d435/infra1/image_rect_raw"
#   ros_type_name: "sensor_msgs/msg/Image"
#   gz_type_name: "gz.msgs.Image"
#   direction: GZ_TO_ROS

# - ros_topic_name: "/d435/infra1/camera_info"
#   gz_topic_name: "/d435/infra1/camera_info"
#   ros_type_name: "sensor_msgs/msg/CameraInfo"
#   gz_type_name: "gz.msgs.CameraInfo"
#   direction: GZ_TO_ROS
# ###########################################################
# ### infra 2 
# - ros_topic_name: "/d435/infra2/image_rect_raw"
#   gz_topic_name: "/d435/infra2/image_rect_raw"
#   ros_type_name: "sensor_msgs/msg/Image"
#   gz_type_name: "gz.msgs.Image"
#   direction: GZ_TO_ROS

# - ros_topic_name: "/d435/infra2/camera_info"
#   gz_topic_name: "/d435/infra2/camera_info"
#   ros_type_name: "sensor_msgs/msg/CameraInfo"
#   gz_type_name: "gz.msgs.CameraInfo"
#   direction: GZ_TO_ROS
# ###########################################################