- ros_topic_name: "/left_front_mecanum_joint/velocity"
  gz_topic_name: "/left_front_mecanum_joint/velocity"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
  lazy: false

- ros_topic_name: "/right_front_mecanum_joint/velocity"
  gz_topic_name: "/right_front_mecanum_joint/velocity"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
  lazy: false

- ros_topic_name: "/left_back_mecanum_joint/velocity"
  gz_topic_name: "/left_back_mecanum_joint/velocity"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
  lazy: false

- ros_topic_name: "/right_back_mecanum_joint/velocity"
  gz_topic_name: "/right_back_mecanum_joint/velocity"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
  lazy: false

- ros_topic_name: "/joint_states"
  gz_topic_name: "/world/default/model/omnibot_robot/joint_state"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS