<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="omnibot_platform">
    <arg name="robot_namespace" default="omnibot_platform"/>
    <xacro:property name="ns" value="$(arg robot_namespace)"/>
    
    <xacro:unless value="${ns == '/' or ns != 'omnibot_manipulator'}">
    <gazebo>
        <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
            <robotNamespace>${ns}</robotNamespace>
        </plugin>
    </gazebo>
</xacro:unless>

    <!-- BASELINK  -->
    <xacro:property name="wheel_base_width" value="0.306100" />
    <xacro:property name="wheel_base_lenth" value="0.336000" />

    <xacro:property name="base_link_offset_x" value="0.0" />
    <xacro:property name="base_link_offset_y" value="0.0" />
    <xacro:property name="base_link_offset_z" value="0.00" />

    <xacro:property name="base_link_rotate_x" value="0.0" />
    <xacro:property name="base_link_rotate_y" value="3.14" />
    <xacro:property name="base_link_rotate_z" value="-1.57" />

    <xacro:property name="base_link_mesh_path"
        value="package://omnibot_platform_description/meshes/ros_base_link.dae" />


    <xacro:property name="base_link_mesh_scale_x" value="0.001" />
    <xacro:property name="base_link_mesh_scale_y" value="0.001" />
    <xacro:property name="base_link_mesh_scale_z" value="0.001" />

    <!-- OMNIWHEEL -->

    <xacro:property name="omniwheel_offset_x" value="${(wheel_base_lenth / 2)}" />
    <xacro:property name="omniwheel_offset_y" value="${(wheel_base_width / 2) + 0.035}" />
    <xacro:property name="omniwheel_offset_z" value="0.015500" />


    <xacro:property name="omniwheel_macro_path"
        value="$(find omnibot_platform_description)/urdf/mecanum_wheel_macro.xacro" />


    <!-- REALSENSE -->
    <xacro:property name="t265_xacro_path"
        value="$(find omnibot_platform_description)/urdf/_t265.urdf.xacro" />

    <xacro:property name="d435_xacro_path"
        value="$(find omnibot_platform_description)/urdf/_d435.urdf.xacro" />

    <xacro:property name="t265_x_offset" value="0.226500" />
    <xacro:property name="t265_y_offset" value="0.0" />
    <xacro:property name="t265_z_offset" value="0.094250" />

    <xacro:property name="t265_x_rotate" value="0.0" />
    <xacro:property name="t265_y_rotate" value="0.0" />
    <xacro:property name="t265_z_rotate" value="0.0" />

    <xacro:property name="d435_x_offset" value="${0.196 + 0.0105 + 0.005}" />
    <xacro:property name="d435_y_offset" value="0.0" />
    <xacro:property name="d435_z_offset" value="0.114" />

    <xacro:property name="d435_x_rotate" value="0.0" />
    <xacro:property name="d435_y_rotate" value="0.0" />
    <xacro:property name="d435_z_rotate" value="0.0" />

    <!-- LIDAR -->
    <xacro:property name="rplidar_a3_xacro_path" 
        value="$(find omnibot_platform_description)/urdf/rplidar_a3.urdf.xacro" />

    <xacro:property name="rplidar_a3_x_offset" value="0.00"/>
    <xacro:property name="rplidar_a3_y_offset" value="0.00"/>
    <xacro:property name="rplidar_a3_z_offset" value="0.00"/>

    <xacro:property name="rplidar_a3_x_rotate" value="0.00"/>
    <xacro:property name="rplidar_a3_y_rotate" value="0.00"/>
    <xacro:property name="rplidar_a3_z_rotate" value="0.00"/>

    <!--  INCLUDES -->
    <xacro:include filename="${omniwheel_macro_path}" />
    <xacro:include filename="${d435_xacro_path}" />
    <xacro:include filename="${t265_xacro_path}" />
    <xacro:include filename="${rplidar_a3_xacro_path}"/>
    <xacro:include filename="$(find omnibot_platform_description)/urdf/inertia_calc.xacro" />


    <!--  PLATFORM DESCRIPTION -->
    <link name="base_footprint"/>

    <link name="base_link">
        <inertial>
            <origin xyz="${base_link_offset_x} ${base_link_offset_y}
        ${base_link_offset_z}"
                rpy="${base_link_rotate_x} ${base_link_rotate_y}
        ${base_link_rotate_z}" />
            <mass value="3.0" />
            <xacro:box_inertia m="3.0" x="${wheel_base_width}" y="${wheel_base_lenth}" z="0.2" />
        </inertial>
        <visual name="">
            <origin xyz="${base_link_offset_x} ${base_link_offset_y} ${base_link_offset_z}"
                rpy="${base_link_rotate_x} ${base_link_rotate_y} ${base_link_rotate_z}" />
            <geometry>
                <mesh filename="${base_link_mesh_path}"
                    scale="${base_link_mesh_scale_x} ${base_link_mesh_scale_y} ${base_link_mesh_scale_z}" />
            </geometry>
            <material name="">
                <color rgba="1.0 0.0 0.0 1.0" />
                <texture filename="" />
            </material>
        </visual>
        <collision>
            <origin xyz="${base_link_offset_x} ${base_link_offset_y} ${base_link_offset_z}"
                rpy="${base_link_rotate_x} ${base_link_rotate_y} ${base_link_rotate_z}" />
            <geometry>
                <mesh filename="${base_link_mesh_path}"
                    scale="${base_link_mesh_scale_x} ${base_link_mesh_scale_y} ${base_link_mesh_scale_z}" />
            </geometry>
        </collision>
    </link>

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_footprint" />
        <child link="base_link" />
        <origin xyz="0.0 0.0 0.08" rpy="0.0 0.0 0.0" />
    </joint>


    <xacro:mecanum_wheel name="left_front" side="1"
        interface="hardware_interface/VelocityJointInterface" parent="base_link">
        <origin xyz="${omniwheel_offset_x} ${omniwheel_offset_y} ${omniwheel_offset_z}"
            rpy="0.0 0.0 1.57" />
    </xacro:mecanum_wheel>

    <xacro:mecanum_wheel name="right_front" side="-1"
        interface="hardware_interface/VelocityJointInterface" parent="base_link">
        <origin xyz="${omniwheel_offset_x} ${-omniwheel_offset_y} ${omniwheel_offset_z}"
            rpy="0.0 0.0 1.57" />
    </xacro:mecanum_wheel>

    <xacro:mecanum_wheel name="left_back" side="-1"
        interface="hardware_interface/VelocityJointInterface" parent="base_link">
        <origin xyz="${-omniwheel_offset_x} ${omniwheel_offset_y} ${omniwheel_offset_z}"
            rpy="0.0 0.0 -1.57" />
    </xacro:mecanum_wheel>

    <xacro:mecanum_wheel name="right_back" side="1"
        interface="hardware_interface/VelocityJointInterface" parent="base_link">
        <origin xyz="${-omniwheel_offset_x} ${-omniwheel_offset_y} ${omniwheel_offset_z}"
            rpy="0.0 0.0 -1.57" />
    </xacro:mecanum_wheel>

    <xacro:sensor_t265 parent="base_link" name="t265" topics_ns="t265"
        odom_xyz="0.0 0.0 0.0" odom_rpy="0.0 0.0 0.0" unite_imu_method="true">
        <origin xyz="${t265_x_offset}  ${t265_y_offset} ${t265_z_offset}" rpy="0 0 0" />
    </xacro:sensor_t265>

    
    <xacro:sensor_d435 parent="base_link" name="d400" topics_ns="d400" align_depth="true" enable_pointCloud="true">
        <origin xyz="${d435_x_offset} ${d435_y_offset}  ${d435_z_offset}" rpy="0.0 0.0 0.0" />
    </xacro:sensor_d435>

    <xacro:rplidar_a3 suffix="front">
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        <parent link="base_link"/>        
    </xacro:rplidar_a3>
</robot>